site_name: Learn To HomeLab
theme: 
  name: material
  favicon: /images/logo/favicon.png
  logo: /images/logo/favicon.png
  font:
    text: Helvetica

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode 
      primary: custom
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: custom
      accent: lime

  plugins:
  
  - social
  - search
  - material
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: hhttps://github.com/LearnToHomeLab
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UChC4ztzEchbm0nxIhw5zyog
  analytics:
    provider: google
    property: G-8W8J33P5JD
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
    - custom.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md #anything at this level will show as a tab at the top of the page
  - Homelab Series:
      - EP 0 - Start Guide: homelabseries/EP0_startguide.md
      - EP 1 - Note Keeping: homelabseries/EP1_notekeeping.md
      - EP 2 - Switch Install: homelabseries/EP2_switch.md
      - EP 3 - Firewall Install: homelabseries/EP3_firewall.md
      - EP 4 - Proxmox Install: homelabseries/EP4_proxmox.md
      - EP 5 - Setting up your first VM: homelabseries/EP5_firstvmubuntu.md
      - EP 6 - Setting up your first Video Game Server (Minecraft Example): homelabseries/EP6_firstvideogameserver.md
      - EP 7 - Set up Pihole with Proxmox: homelabseries/EP7_setuppihole.md  
      - EP 8 - NextCloud Install with Proxmox: homelabseries/EP8_nextcloud.md
      - EP 9 - Tailscale Install with Proxmox: homelabseries/EP9_tailscale.md
      - EP 10 - Zabbix Server Install with Proxmox: homelabseries/EP10_zabbixserver.md
      - EP 11 - Zabbix Agent Install on a VM: homelabseries/EP11_zabbixagent.md
      - EP 12 - Zabbix - How to Create Dashboards: homelabseries/EP12_zabbixdashboards.md
      - EP 13 - How to Install The Homarr Dashboard: homelabseries/EP13_homarr.md
      - EP 14 - Get Proxmox Stats In Homarrs Dashboard: homelabseries/EP14_homarr.md
      - EP 15 - How to Install The Wazuh Server: homelabseries/EP15_wazuhserver.md
      - EP 16 - Install the Wazuh Agent: homelabseries/EP16_wazuhagent.md
      - EP 17 - Install Truenas Scale: homelabseries/EP17_truenasscale.md
      - EP 18 - Install NextCloud on TrueNas: homelabseries/EP18_trunasnextcloud.md
      - EP 19 - Wazuh Discord Alerts: homelabseries/EP19_wazuhdiscordalerts.md
      - EP 20 - Proxmox Cluster Setup: homelabseries/EP20_ProxmoxClustering.md
      - EP 21 - Proxmox Live VM Migration (ceph): homelabseries/EP21_ProxmoxCeph.md
      - EP 22 - Homarr 1.0 Install/Upgrade: homelabseries/EP22_homarr1.0upgrade.md
      - EP 23 - Note Taking with NextCloud: homelabseries/EP23_notesinnextcloud.md
      - EP 24 - JellyFin on TrueNas:  homelabseries/EP24_jellyFin.md
      - EP 25 - Pterodactyl Game Panel: homelabseries/EP25_Pterodactylinstall.md
      - EP 26 - Nginx Proxy Manager: homelabseries/EP26_nginxproxymanagerssl.md
      - EP 27 - Install Docmost: homelabseries/EP27_docmost.md
      - EP 28 - Install Vaultwarden: homelabseries/EP28_vaultwarden.md
      - EP 29 - Install Cockpit: homelabseries/EP29_cockpit.md
      - EP 30 - Actual Budget: homelabseries/EP30_actualbudget.md
      - EP 31 - CloudFlare Tunnels: homelabseries/EP31_cloudflaretunnels.md
      - EP 32 - Automatic Security Updates: homelabseries/EP33_AutomaticSecurityUpdates.md
      - EP 34 - Enable SSH Key Authentication: homelabseries/EP34_SSHKeyAuthentication.md
      - EP 35 - Linux Firewall Setup (UFW): homelabseries/EP35_LinuxUFW.md
      - EP 36 - Install Fail2Ban on Linux: homelabseries/EP36_fail2baninstall.md
      - EP 37 - Remove Unnecessary/Unused Linux Packages: homelabseries/EP37_RemovelinuxPackages.md
      - EP 38 - Upload SSH Keys to GitHub and Manage them: homelabseries/EP38_SSHKeysGithub.md
      - EP 39 - Move Proxmox VMs & Containers to a New Storage Drive: homelabseries/EP39_MovingProxmoxVMStorage.md
  - Linux Master Guide:
      - EP1 - Create Linux Environment: LinuxMasterGuide/EP1_CreateLinuxEnvironment.md
      
  # - Basic Networking:
  #    - EP 1 - Configuring Cisco Switches: BasicNetworking/EP1_switchconfiguration.md
  - Hardware Reviews:
      - EP 0 - Unifi Flex Mini 2.5G: hardwarereview/ep0_unififlex2gig.md
  - Software Tutorials:
      - Affine Workspaces: softwaretutorials/affineorkspaces.md
    
copyright: |
  &copy; 2024-2025 <a href="https://www.youtube.com/channel/UChC4ztzEchbm0nxIhw5zyog"  target="_blank" rel="noopener">Learn To Homelab</a>